services:
  - type: web
    name: image-compression-service
    env: node
    plan: free
    branch: master  # or main depending on your repo
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

